### ISSUE TITLE
Version 3.2.1 doesn't seem to be available on ansible galaxy

### ISSUE THREAD

**Issue by rnestler** [hifis-net/ansible-role-unattended-upgrades#169]
I can find 3.2.1 on GitHub: https://github.com/hifis-net/ansible-role-unattended-upgrades/releases/tag/v3.2.1, but not on ansible galaxy: https://galaxy.ansible.com/ui/standalone/roles/hifis/unattended_upgrades/

**Comment by Normo** [comment]
Hello @rnestler, due to shortcomings in the new Ansible Galaxy, we are currently unable to import new releases. We are sorry for this inconvenience. Please use GitHub as a source for the role as a workaround:

```yaml
roles:
  - name: "hifis.unattended_upgrades"
    src: "https://github.com/hifis-net/ansible-role-unattended-upgrades"
    version: "v3.2.1"
```
