### ISSUE TITLE
v4.0.0 release summary

### ISSUE THREAD

**Issue by Normo** [hifis-net/ansible-role-unattended-upgrades#207]
**UPGRADE NOTES AND BREAKING CHANGES:**

The `hifis.unattended_upgrades` role has been migrated to the `hifis.toolkit` collection. Please ensure that you install the new collection as follows:

```sh
ansible-galaxy collection install hifis.toolkit
```

To continue using the [`unattended_upgrades`](roles/unattended_upgrades) role as before, please include it as described:

```yaml
- hosts: all
  roles:
     - role: hifis.toolkit.unattended_upgrades
```
