### ISSUE TITLE
`unattended_dl_limit` doesn't work

### ISSUE THREAD

**Issue by Encephala** [hifis-net/ansible-role-unattended-upgrades#76]
I have passed `unattended_dl_limit: 40000` to the role:
```yaml
- name: Set Unattended upgrades
  ansible.builtin.import_role:
    name: hifis.unattended_upgrades
  vars:
    unattended_dl_limit: 40000
  when: ansible_facts['os_family'] == 'Debian'
```

But after running the playbook successfully, the change is not made in the `50unattended-upgrades` file on the destination:

```bash
// Use apt bandwidth limit feature, this example limits the download
// speed to 70kb/sec
//Acquire::http::Dl-Limit "70";
```

Looking at the defaults for the role, I noticed that `unattended_dl_limit` is commented out (see below), so perhaps you are already aware of this, but I can't find any mention of it in the repo's README, so I figured I'd share anyways to be sure :)

```yaml
# Use apt bandwidth limit feature, this example limits the download speed to 70kb/sec
#unattended_dl_limit: 70
```

I would love if this feature were implemented again!
